# This is the standard .bash_profile for all package users. You can
# change it however you like based on your own preferences.  There are a
# few suggested customizations embedded below; uncomment lines as
# appropriate. Don't feel like you have to keep these comments after
# you're happy with the result -- I always delete them to reduce
# clutter!

# it can be nice to source the system bashrc to get features like
# completions and dircolors, but do this with caution.  Variables
# introduced by doing this could have an undesired impact on package
# builds.
# if [ -f /etc/bashrc ]; then
#     . /etc/bashrc
# fi

# The wrappers directory must be the first entry in the PATH.
export PATH=/usr/lib/pkgusr:/bin:/usr/bin:/usr/X11R6/bin:/sbin:/usr/sbin

# The /bootstrap binary directories must be the last part of the PATH
# (so that the final system components are used as they are built), and
# should be removed entirely after the CBL build is complete (at which
# point /bootstrap is no longer needed and should be deleted).
export PATH=${PATH}:/bootstrap/bin:/bootstrap/sbin

# Make the shell prompt reflect that we are a package user.
export PROMPT_COMMAND='PS1="package \u:"`pwd`"> "'
# Alternatively, make it stand out more with color
# NORMAL="\[\e[0m\]"
# GREEN="\[\e[0;32m\]"
# export PROMPT_COMMAND='PS1="package $GREEN\u$NORMAL:"`pwd`"$GREEN>$NORMAL "'

# add more pkg-config dirs as they are created.
export PKG_CONFIG_PATH=/usr/lib/pkgconfig

if [ -x "$HOME/options" ]
then
    source $HOME/options
else
    if [ -f "$HOME/options" ]
    then
        echo '`options` file exists but is not executable!'
        echo 'It will be ignored. `chmod +x` it if you want it to be used.'
    fi
fi

export -f initial_checkup
export -f configure_commands make_commands test_commands install_commands

# Go to the home directory whenever we su to a package user.
cd

# Add optimizations by default.  Unset or override these variables
# globally here, and on a per-package basis by modifying ~/options.
