# The wrappers directory must be the first entry in the PATH.
export PATH=/usr/lib/pkgusr:/bin:/usr/bin:/usr/X11R6/bin:/sbin:/usr/sbin

# The /tools/bin directory must be the last entry in the PATH.  This 
# can (and should) be removed after the LFS build is complete 
# (and /tools is no longer needed)
export PATH=${PATH}:/tools/bin

# Make prompt reflect that we are a package user.
export PROMPT_COMMAND='PS1="package \u:"`pwd`"> "'

# Add optimizations by default.  Unset or override these
# variables globally here, and on a per-package basis by modifying
# ~/options.
export CHOST="i686-pc-linux-gnu"
export CFLAGS="-march=prescott -O3 -pipe -fomit-frame-pointer"
export CXXFLAGS="${CFLAGS}"

# add more pkgconfig dirs as they are created.
export PKG_CONFIG_PATH=/usr/lib/pkgconfig

# default build commands -- override these in $HOME/options as
# needed for particular packages.
function configure_commands()
{
  ./configure --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install
}

if [ -x "$HOME/options" ]
then
    . $HOME/options
else
    if [ -f "$HOME/options" ]
    then
        echo "options file exists but is not executable!  Please fix that."
    fi
fi

export -f configure_commands make_commands test_commands install_commands

# Go to the home directory whenever we su to a package user.
cd

