#!/bin/bash

# pre-create all package users for the basic LFS system
add_package_user "Linux Kernel Headers" kernel-headers &&
add_package_user "Manual pages" man-pages &&
add_package_user "GNU libc" glibc &&
add_package_user "GNU m4 macro processor" m4 &&
add_package_user "GNU multi-precision arithmetic library" gmp &&
add_package_user "MPFR math library" mpfr &&
add_package_user "GNU binutils" binutils &&
add_package_user "GNU compiler collection" gcc &&
add_package_user "GNU Stream EDitor" sed &&
add_package_user "ext2 filesystem programs" e2fsprogs &&
add_package_user "GNU core utilities" coreutils &&
add_package_user "IANA etc files" iana-etc &&
add_package_user "GNU bison" bison &&
add_package_user ncurses ncurses &&
add_package_user procps procps &&
add_package_user "GNU library tool" libtool &&
add_package_user flex flex &&
add_package_user "IP routing tool" iproute2 &&
add_package_user perl perl &&
add_package_user "GNU readline" readline &&
add_package_user zlib zlib &&
add_package_user "GNU autoconf" autoconf &&
add_package_user "GNU automake" automake &&
add_package_user "GNU Bourne-Again SHell" bash &&
add_package_user bzip2 bzip2 &&
add_package_user "GNU difference utilities" diffutils &&
add_package_user "File type analyzer" file &&
add_package_user "GNU file finding utilities" findutils &&
add_package_user "GNU awk" gawk &&
add_package_user "GNU gettext" gettext &&
add_package_user "GNU grep" grep &&
add_package_user "GNU groff" groff &&
add_package_user "GNU zip" gzip &&
add_package_user "GNU network utilities" inetutils &&
add_package_user kbd kbd &&
add_package_user less less &&
add_package_user "GNU make" make &&
add_package_user "manual viewer" man &&
add_package_user "module init tools" module-tools &&
add_package_user "GNU patch" patch &&
add_package_user psmisc psmisc &&
add_package_user "shadow password tools" shadow &&
add_package_user "system logger" sysklogd &&
add_package_user "UNIX System V init" sysvinit &&
add_package_user "GNU tar" tar &&
add_package_user "GNU texinfo" texinfo &&
add_package_user "Device node manager" udev &&
add_package_user "Misc Linux utilities" util-linux-ng &&
add_package_user "Vi IMproved" vim &&
add_package_user "GRand Unified Bootloader" grub &&
add_package_user "Linux Kernel" kernel &&
rm -f $0
