#!/bin/bash
# Copyright (c) 2015 Eric Herman <eric AT freesa DOT org>
# and Brett Neumeier <random AT freesa DOT org>
# Licensed under the terms of GNU General Public License version 3 or later
# Provided `as is' with absolutely no warranty of any kind.

if [ $# -ne 1 ]; then
  echo 1>&2
  echo 1>&2 'USAGE: monitor_build <package_name>'
  echo 1>&2
  exit 1
fi

PACKAGE=$1

if [ ! -d /usr/src/$PACKAGE ]
then
    exit 1
fi

cd /usr/src/$PACKAGE

while $(pgrep -u $PACKAGE -f build)
do
  LOG=$(ls -d1 /usr/src/$PACKAGE/0* | tail -n 1)
  export L=$(($(tput lines) - 1))
  clear
  ls -l $LOG
  tail -n $L $LOG | elide_middle
  sleep 2;
done
